export enum ModelsEnum {
  ASSIGNED_COURSES = 'assigned_courses',
  CONTACT = 'contact',
  COURSE_CATEGORIES = 'course_categories',
  COURSES = 'courses',
  EXAM_RESULTS = 'exam_results',
  EXAMS = 'exams',
  HOMEWORK_SUBMISSIONS = 'homework_submissions',
  HOMEWORKS = 'homeworks',
  LAST_ACTIVITY = 'last_activity',
  LESSON_FILES = 'lesson_files',
  LESSON_MODULES = 'lesson_modules',
  LESSON_VIEWS = 'lesson_views',
  LESSONS = 'lessons',
  MENTOR_PROFILES = 'mentor_profiles',
  PERMISSIONS = 'permissions',
  PURCACHED_COURSES = 'purcached_courses', // Ehtimol bu "purchased_courses" bo'lishi kerak
  QUESTION_ANSWERS = 'question_answers',
  QUESTIONS = 'questions',
  RATING = 'rating',
  USERS = 'users',
}
import { PrismaClient } from '@prisma/client';

export enum ModelsEnumInPrisma {
  ASSIGNED_COURSES = 'assignedCourse',
  CONTACT = 'contact',
  COURSE_CATEGORIES = 'courseCategory',
  COURSES = 'course',
  EXAM_RESULTS = 'examResult',
  EXAMS = 'exam',
  HOMEWORK_SUBMISSIONS = 'homeworkSubmission',
  HOMEWORKS = 'homework',
  LAST_ACTIVITY = 'lastActivity',
  LESSON_FILES = 'lessonFile',
  LESSON_MODULES = 'lessonModul',
  LESSON_VIEWS = 'lessonView',
  LESSONS = 'lesson',
  MENTOR_PROFILES = 'mentorProfile',
  PERMISSIONS = 'permission',
  PURCACHED_COURSES = 'purcachedCourse',
  QUESTION_ANSWERS = 'questionAnswer',
  QUESTIONS = 'question',
  RATING = 'rating',
  USERS = 'user',
}

export const prismaModelMap: Record<ModelsEnumInPrisma, keyof PrismaClient> = {
  [ModelsEnumInPrisma.ASSIGNED_COURSES]: 'assignedCourse',
  [ModelsEnumInPrisma.CONTACT]: 'contact',
  [ModelsEnumInPrisma.COURSE_CATEGORIES]: 'courseCategory',
  [ModelsEnumInPrisma.COURSES]: 'course',
  [ModelsEnumInPrisma.EXAM_RESULTS]: 'examResult',
  [ModelsEnumInPrisma.EXAMS]: 'exam',
  [ModelsEnumInPrisma.HOMEWORK_SUBMISSIONS]: 'homeworkSubmission',
  [ModelsEnumInPrisma.HOMEWORKS]: 'homework',
  [ModelsEnumInPrisma.LAST_ACTIVITY]: 'lastActivity',
  [ModelsEnumInPrisma.LESSON_FILES]: 'lessonFile',
  [ModelsEnumInPrisma.LESSON_MODULES]: 'lessonModul',
  [ModelsEnumInPrisma.LESSON_VIEWS]: 'lessonView',
  [ModelsEnumInPrisma.LESSONS]: 'lesson',
  [ModelsEnumInPrisma.MENTOR_PROFILES]: 'mentorProfile',
  [ModelsEnumInPrisma.PERMISSIONS]: 'permission',
  [ModelsEnumInPrisma.PURCACHED_COURSES]: 'purcachedCourse',
  [ModelsEnumInPrisma.QUESTION_ANSWERS]: 'questionAnswer',
  [ModelsEnumInPrisma.QUESTIONS]: 'question',
  [ModelsEnumInPrisma.RATING]: 'rating',
  [ModelsEnumInPrisma.USERS]: 'user',
};
